#we use java
language: java
#we add the java development kit (jdk)

jdk:
  - oraclejdk11

services:
  - mysql
  
before_install:
 - chmod +x mvnw

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS zzpj;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS zzpj;'
